# Execute on the latest Angular runner
image: gitlab.e1c.net:4567/platform/ci-runners/angular:latest


# If this is the main branch, first increment the semver; in all cases, build
# and test the branch, and then publish and deploy (just the main branch)
stages:
  - increment-version
  - publish-branch-build
  - publish-versioned-build
  - deploy-versioned-build


# Grab the helper scripts, and make sure variables are set
before_script:
  - git clone --depth 1 git@gitlab.e1c.net:platform/ci-scripts.git
  - source ci-scripts/set-variables.sh


# Increment the semantic version and tag the repository with it
increment-version:
  stage: increment-version
  only:
    - branches
  script:
    - ci-scripts/increment-version.sh


# Construct a Docker image from the code, test it, and
# if everything looks good push it to the Docker registry
publish-branch-build:
  stage: publish-branch-build
  only:
    - branches
  script:
    - ci-scripts/build-image.sh
    - ci-scripts/test-image.sh
    - ci-scripts/push-image.sh


# Tag the image with the semver and push it; also push a latest image
publish-versioned-build:
  stage: publish-versioned-build
  only:
    - branches
  script:
    - ci-scripts/publish-version.sh


# Deploy the latest image to a development environment
deploy-versioned-build:
  stage: deploy-versioned-build
  only:
    - branches
  environment:
    name: evs-voting-tools
    url: https://voting.evs-tools.e1c.net
  script:
    - ci-scripts/deploy-version.sh
